{{- if not .Values.rollout.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels: { app: {{ include "app.fullname" . }} }
  template:
    metadata:
      labels: { app: {{ include "app.fullname" . }} }
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
     {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
{{- end }}
