{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
  strategy:
    canary:
      stableService: {{ include "app.fullname" . }}-stable
      canaryService: {{ include "app.fullname" . }}-canary
      trafficRouting:
        alb:
          ingress: {{ include "app.fullname" . }}
          servicePort: {{ .Values.service.port }}
      steps:
        - setWeight: 10
        - pause:
            duration: 60
        - setWeight: 50
        - pause: {}
        - setWeight: 100
{{- end }}
