apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
spec:
  selector: { app: {{ include "app.fullname" . }} }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
