{{- if .Values.rollout.enabled }}
  piVersion: v1
  kind: Service
  metadata:
    name: {{ include "app.fullname" . }}-canary
  spec:
    ports:
      - port: {{ .Values.service.port }}
        targetPort: {{ .Values.service.port }}
    selector:
      app: {{ include "app.fullname" . }}
{{- end }}