apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name kinesis_streams
        Match *
        region ap-northeast-2
        stream eks-logs-buffer
        time_key @timestamp
        time_key_format %Y-%m-%dT%H:%M:%S.%L%z
        
  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
        
  filters.conf: |
    [FILTER]
        Name parser
        Match *
        Key_Name log
        Parser docker
        Reserve_Data true
        Preserve_Key true
