apiVersion: v1
kind: ConfigMap
metadata:
  name: complete-configmap
  namespace: dev
data:
  # Database Hosts - 실제 RDS 엔드포인트
  ADMIN_DB_HOST: eatcloud-dev-admin.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  ADMIN_DB_NAME: admin_db
  AUTH_DB_HOST: eatcloud-dev-auth.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  AUTH_DB_NAME: auth_db
  CUSTOMER_DB_HOST: eatcloud-dev-customer.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  CUSTOMER_DB_NAME: customer_db
  MANAGER_DB_HOST: eatcloud-dev-manager.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  MANAGER_DB_NAME: manager_db
  ORDER_DB_HOST: eatcloud-dev-cart.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  ORDER_DB_NAME: order_db
  PAYMENT_DB_HOST: eatcloud-dev-payment.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  PAYMENT_DB_NAME: payment_db
  
  # Database Common Settings
  DB_PORT: "5432"
  DB_USERNAME: eatcloud_user
  
  # Spring Profiles - AWS 환경으로 설정 (Eureka 비활성화)
  SPRING_PROFILES_ACTIVE: aws
  
  # Eureka Settings (aws 프로파일에서는 비활성화됨)
  EUREKA_CLIENT_ENABLED: "false"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  
  # Redis Settings
  REDIS_DATABASE: "0"
  REDIS_HOST: eatcloud-redis
  REDIS_POOL_MAX_ACTIVE: "8"
  REDIS_POOL_MAX_IDLE: "8"
  REDIS_POOL_MIN_IDLE: "0"
  REDIS_PORT: "6379"
  REDIS_SSL_ENABLED: "false"
  REDIS_TIMEOUT: 10000ms
  SPRING_DATA_REDIS_HOST: eatcloud-redis
  SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE: "8"
  SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE: "8"
  SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE: "0"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_SSL_ENABLED: "false"
  SPRING_DATA_REDIS_TIMEOUT: 10000ms
  
  # Kafka Settings
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: '*'
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  
  # JPA/Hibernate Settings
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_SQL_INIT_MODE: always
  
  # Session/Security Settings
  SPRING_SESSION_REDIS_FLUSH_MODE: on_save
  SPRING_SESSION_REDIS_NAMESPACE: eatcloud:session
  SPRING_SESSION_STORE_TYPE: redis
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-service:8081/api/v1/auth/.well-known/jwks.json
  
  # Mail Settings
  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: smtp
  SPRING_MAIL_USERNAME: profect.eatcloud@gmail.com
  
  # Cloud/Discovery Settings
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  
  # Management/Actuator Settings
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  
  # Logging Settings
  LOGGING_LEVEL_COM_EATCLOUD: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_CONFIG: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CORE_ENV: DEBUG
  
  # Server Settings
  SERVER_FORWARD_HEADERS_STRATEGY: framework
  
  # Payment Settings
  PAYMENT_MOCK_ENABLED: "true"
