apiVersion: v1
kind: ConfigMap
metadata:
  name: complete-configmap
  namespace: dev
data:
  # Database Hosts - 실제 RDS 엔드포인트
  ADMIN_DB_HOST: eatcloud-dev-admin.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  ADMIN_DB_NAME: admindb
  AUTH_DB_HOST: eatcloud-dev-auth.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  AUTH_DB_NAME: authdb
  CUSTOMER_DB_HOST: eatcloud-dev-customer.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  CUSTOMER_DB_NAME: customerdb
  MANAGER_DB_HOST: eatcloud-dev-manager.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  MANAGER_DB_NAME: managerdb
  ORDER_DB_HOST: eatcloud-dev-cart.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  ORDER_DB_NAME: cartdb
  PAYMENT_DB_HOST: eatcloud-dev-payment.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  PAYMENT_DB_NAME: paymentdb
  STORE_DB_HOST: eatcloud-dev-store.cnikgsy08gto.ap-northeast-2.rds.amazonaws.com
  STORE_DB_NAME: storedb
  
  # Database Common Settings
  DB_PORT: "5432"
  DB_USERNAME: dbadmin
  
  # Spring Profiles - AWS 환경으로 설정 (Eureka 비활성화)
  SPRING_PROFILES_ACTIVE: aws
  
  # Eureka Settings (aws 프로파일에서는 비활성화됨)
  EUREKA_CLIENT_ENABLED: "false"
  EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  
  # Redis Settings - 실제 ElastiCache 엔드포인트
  REDIS_DATABASE: "0"
  REDIS_HOST: eatcloud-redis-ha.dfenr7.ng.0001.apn2.cache.amazonaws.com
  REDIS_POOL_MAX_ACTIVE: "8"
  REDIS_POOL_MAX_IDLE: "8"
  REDIS_POOL_MIN_IDLE: "0"
  REDIS_PORT: "6379"
  REDIS_SSL_ENABLED: "false"
  REDIS_TIMEOUT: 10000ms
  SPRING_DATA_REDIS_HOST: eatcloud-redis-ha.dfenr7.ng.0001.apn2.cache.amazonaws.com
  SPRING_DATA_REDIS_LETTUCE_POOL_MAX_ACTIVE: "8"
  SPRING_DATA_REDIS_LETTUCE_POOL_MAX_IDLE: "8"
  SPRING_DATA_REDIS_LETTUCE_POOL_MIN_IDLE: "0"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_SSL_ENABLED: "false"
  SPRING_DATA_REDIS_TIMEOUT: 10000ms
  
  # Kafka Settings - 실제 MSK 클러스터 엔드포인트 (TLS 9094 포트)
  KAFKA_BOOTSTRAP_SERVERS: b-1.eatcloudmskkraft.0di85t.c3.kafka.ap-northeast-2.amazonaws.com:9094,b-2.eatcloudmskkraft.0di85t.c3.kafka.ap-northeast-2.amazonaws.com:9094
  SPRING_KAFKA_BOOTSTRAP_SERVERS: b-1.eatcloudmskkraft.0di85t.c3.kafka.ap-northeast-2.amazonaws.com:9094,b-2.eatcloudmskkraft.0di85t.c3.kafka.ap-northeast-2.amazonaws.com:9094
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: '*'
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
  
  # Kafka TLS/SSL Settings - TLS 연결을 위한 설정
  SPRING_KAFKA_SECURITY_PROTOCOL: SSL
  SPRING_KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  SPRING_KAFKA_CONSUMER_PROPERTIES_SECURITY_PROTOCOL: SSL
  SPRING_KAFKA_CONSUMER_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  SPRING_KAFKA_PRODUCER_PROPERTIES_SECURITY_PROTOCOL: SSL
  SPRING_KAFKA_PRODUCER_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  
  # JPA/Hibernate Settings
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"
  SPRING_JPA_HIBERNATE_DDL_AUTO: none
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_SQL_INIT_MODE: always
  
  # Session/Security Settings
  SPRING_SESSION_REDIS_FLUSH_MODE: on_save
  SPRING_SESSION_REDIS_NAMESPACE: eatcloud:session
  SPRING_SESSION_STORE_TYPE: redis
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://auth-service:8081/api/v1/auth/.well-known/jwks.json
  
  # Mail Settings
  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_DEBUG: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_PROPERTIES_MAIL_TRANSPORT_PROTOCOL: smtp
  SPRING_MAIL_USERNAME: profect.eatcloud@gmail.com
  
  # Cloud/Discovery Settings
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  
  # Management/Actuator Settings - Health Check 수정
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  
  # Logging Settings
  LOGGING_LEVEL_COM_EATCLOUD: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_CONTEXT_CONFIG: DEBUG
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CORE_ENV: DEBUG
  
  # Server Settings
  SERVER_FORWARD_HEADERS_STRATEGY: framework
  
  # Payment Settings
  PAYMENT_MOCK_ENABLED: "true"
  
  # Java Memory Settings
  JAVA_OPTS: "-Xms512m -Xmx1536m -XX:+UseG1GC"
