# Updated ConfigMap for dev namespace (simplified)
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: dev
data:
  # Spring Profiles
  SPRING_PROFILES_ACTIVE: "dev"
  
  # Server Configuration
  SERVER_PORT: "8080"
  
  # H2 Database (임시)
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:testdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: ""
  
  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_H2_CONSOLE_ENABLED: "true"
  
  # Eureka Configuration (비활성화)
  EUREKA_CLIENT_ENABLED: "false"
  SPRING_CLOUD_DISCOVERY_ENABLED: "false"
  
  # Logging Configuration
  LOGGING_LEVEL_COM_EATCLOUD: "DEBUG"
  LOGGING_LEVEL_ROOT: "INFO"
  
  # Management Endpoints
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"

---
# Auth Service Deployment with ECR
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: dev
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 536580887516.dkr.ecr.ap-northeast-2.amazonaws.com/eatcloud/auth-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SERVER_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: EUREKA_CLIENT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_CLIENT_ENABLED
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
# Auth Service Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: dev
  labels:
    app: auth-service
spec:
  ports:
  - port: 8081
    targetPort: 8080
    name: http
  selector:
    app: auth-service
  type: ClusterIP
