apiVersion: v1
kind: Service
metadata:
  name: auth-db
  namespace: eatcloud
  labels:
    app: auth-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: auth-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: eatcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_USER
          value: "eatcloud_user"
        - name: POSTGRES_PASSWORD
          value: "devpassword123"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: postgres-data
        emptyDir: {}
