# Store, Customer, Admin, Manager 서비스용 간단한 데이터베이스들
apiVersion: v1
kind: Service
metadata:
  name: store-db
  namespace: eatcloud
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: store-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-db
  namespace: eatcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-db
  template:
    metadata:
      labels:
        app: store-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "store_db"
        - name: POSTGRES_USER
          value: "eatcloud_user"
        - name: POSTGRES_PASSWORD
          value: "devpassword123"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: eatcloud
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: customer-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  namespace: eatcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "customer_db"
        - name: POSTGRES_USER
          value: "eatcloud_user"
        - name: POSTGRES_PASSWORD
          value: "devpassword123"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
      volumes:
      - name: postgres-data
        emptyDir: {}
