apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: eatcloud
  labels:
    app: payment-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: payment-db
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
  namespace: eatcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "payment_db"
        - name: POSTGRES_USER
          value: "eatcloud_user"
        - name: POSTGRES_PASSWORD
          value: "devpassword123"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - eatcloud_user
            - -d
            - payment_db
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - eatcloud_user
            - -d
            - payment_db
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 5
      volumes:
      - name: postgres-data
        emptyDir: {}
