apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: dev
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        Health_Check  On

    # 테스트용 로그 수집 (로컬 파일로만)
    [INPUT]
        Name              tail
        Tag               eatcloud.test
        Path              /var/log/app/*.log
        Parser            json
        DB                /fluent-bit/tail/test.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    # 로컬 파일 출력 (테스트용)
    [OUTPUT]
        Name  file
        Match eatcloud.test
        Path  /fluent-bit/logs/output.log

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%3N
        Time_Keep   On

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit-service-account
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
    - nodes
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-role
subjects:
- kind: ServiceAccount
  name: fluent-bit-service-account
  namespace: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-test
  namespace: dev
  labels:
    app: admin-service-test
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service-test
  template:
    metadata:
      labels:
        app: admin-service-test
        version: v1
    spec:
      serviceAccountName: fluent-bit-service-account
      containers:
      # 메인 애플리케이션 컨테이너
      - name: admin-service
        image: 536580887516.dkr.ecr.ap-northeast-2.amazonaws.com/eatcloud/admin-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: LOG_PATH
          value: "/var/log/app"
        - name: SPRING_APPLICATION_NAME
          value: "admin-service"
        # 추천 이벤트 로깅 활성화
        - name: LOGGING_RECOMMENDATION_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: complete-configmap
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/app
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

      # Fluent Bit 사이드카 컨테이너
      - name: fluent-bit
        image: fluent/fluent-bit:2.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
          name: http-metrics
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: app-logs
          mountPath: /var/log/app
          readOnly: true
        - name: fluent-bit-db
          mountPath: /fluent-bit/tail
        - name: fluent-bit-output
          mountPath: /fluent-bit/logs
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 10
          periodSeconds: 10

      volumes:
      # 로그 파일 공유 볼륨
      - name: app-logs
        emptyDir: {}
      # Fluent Bit DB 볼륨
      - name: fluent-bit-db
        emptyDir: {}
      # Fluent Bit 출력 볼륨
      - name: fluent-bit-output
        emptyDir: {}
      # Fluent Bit 설정
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-test
  namespace: dev
  labels:
    app: admin-service-test
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  - port: 2020
    targetPort: 2020
    protocol: TCP
    name: metrics
  selector:
    app: admin-service-test
  type: ClusterIP
