apiVersion: v1
kind: Service
metadata:
  name: eatcloud-redis
  namespace: eatcloud
  labels:
    app: eatcloud-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: eatcloud-redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatcloud-redis
  namespace: eatcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eatcloud-redis
  template:
    metadata:
      labels:
        app: eatcloud-redis
    spec:
      containers:
      - name: redis
        image: redis:7.4-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - 512mb
        - --maxmemory-policy
        - allkeys-lru
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: eatcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
