  USER-SUPPLIED VALUES:
  backend:
    replicas: 0
  deploymentMode: SingleBinary
  gateway:
    enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-scheme: internal
        service.beta.kubernetes.io/aws-load-balancer-target-type: ip
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
      port: 3100
      targetPort: 8080
      type: LoadBalancer
  loki:
    commonConfig:
      replication_factor: 1
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      allow_structured_metadata: false
    memberlist:
      join_members: []
    schemaConfig:
      configs:
        - from: "2020-10-24"
          index:
            period: 24h
            prefix: index_
          object_store: s3
          schema: v11
          store: boltdb-shipper
    storage:
      bucketNames:
        chunks: eatcloud-loki-storage-12345
        ruler: eatcloud-loki-storage-12345
      s3:
        endpoint: ""
        region: ap-northeast-2
      type: s3
  read:
    replicas: 0
  serviceAccount:
    create: false
    name: loki-sa
  singleBinary:
    extraVolumeMounts:
      - mountPath: /var/loki
        name: loki-storage
    extraVolumes:
      - emptyDir: {}
        name: loki-storage
    persistence:
      enabled: false
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  write:
    replicas: 0
