# Loki Values for EKS Deployment
# Optimized for Vector → Loki pipeline

loki:
  # Basic configuration
  auth_enabled: false

  server:
    http_listen_port: 3100
    grpc_listen_port: 9095

  common:
    path_prefix: /var/loki
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    replication_factor: 1
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory

  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks

  compactor:
    working_directory: /var/loki/boltdb-shipper-compactor
    shared_store: filesystem

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    ingestion_rate_mb: 32
    ingestion_burst_size_mb: 64
    max_streams_per_user: 10000
    max_line_size: 256000
    retention_period: 720h  # 30 days

  chunk_store_config:
    max_look_back_period: 0s

  table_manager:
    retention_deletes_enabled: true
    retention_period: 720h

# Deployment configuration
deploymentMode: SingleBinary

singleBinary:
  replicas: 1

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  persistence:
    enabled: true
    storageClass: gp2
    size: 50Gi

  nodeSelector: {}
  tolerations: []

  extraArgs:
    - -config.expand-env=true

  extraEnv:
    - name: JAEGER_AGENT_HOST
      value: ""
    - name: JAEGER_SAMPLER_TYPE
      value: ""

# Services
gateway:
  enabled: false

# Monitoring
monitoring:
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

# Test pods
test:
  enabled: false

# Network policy
networkPolicy:
  enabled: false