# 3-loki-values.yaml (게이트웨이 방식 최종 완성본)

# 1. 배포 모드 및 다른 모드 비활성화
deploymentMode: SingleBinary
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# 2. IRSA를 위한 서비스 계정 설정
serviceAccount:
  create: false
  name: loki-sa # eksctl로 생성한 이름 사용

# 3. singleBinary 배포 설정
singleBinary:
  replicas: 1
  persistence:
    enabled: false

# 4. [핵심] Gateway를 활성화하고, Gateway의 서비스를 LoadBalancer로 설정
gateway:
  enabled: true
  service:
    type: LoadBalancer
    port: 3100
    targetPort: 80
    annotations:
      # Fargate 환경을 위한 핵심 설정
      service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
      # 내부 NLB 설정
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

# 5. Loki 핵심 설정
loki:
  storage:
    type: 's3'
    bucketNames:
      # 여기에 Loki 전용으로 생성한 S3 버킷 이름을 입력하세요.
      chunks: "eatcloud-loki-storage-12345"
      ruler: "eatcloud-loki-storage-12345"
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h