{{- if eq .Values.deployment.type "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentBit.name | default "fluent-bit" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: fluent-bit
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: fluent-bit
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: fluent-bit
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      containers:
      - name: fluent-bit
        image: {{ .Values.fluentBit.image.repository }}:{{ .Values.fluentBit.image.tag }}
        imagePullPolicy: {{ .Values.fluentBit.image.pullPolicy }}
        ports:
        - containerPort: 2020
          name: http-metrics
        volumeMounts:
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-db
          mountPath: /fluent-bit/tail
        resources:
{{ toYaml .Values.fluentBit.resources | indent 10 }}
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-db
        emptyDir: {}
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
{{- end }}
