apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: eatcloud
  labels:
    app: auth-service
    service: business
spec:
  ports:
  - port: 8081
    targetPort: 8080
    name: http
  selector:
    app: auth-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: eatcloud
  labels:
    app: auth-service
    service: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        service: business
    spec:
      containers:
      - name: auth-service
        image: eatcloud/auth-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_PROFILES_ACTIVE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: AUTH_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: auth-db-config
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: REDIS_PORT
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_CLIENT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_CLIENT_ENABLED
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MAIL_PASSWORD
        - name: SPRING_MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_MAIL_HOST
        - name: SPRING_MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_MAIL_PORT
        - name: SPRING_MAIL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_MAIL_USERNAME
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
