apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: eatcloud
  labels:
    app: eureka-server
    service: discovery
spec:
  ports:
  - port: 8761
    targetPort: 8761
    name: eureka
  selector:
    app: eureka-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: eatcloud
  labels:
    app: eureka-server
    service: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        service: discovery
    spec:
      containers:
      - name: eureka-server
        image: eatcloud/eureka-server:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_PROFILES_ACTIVE
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
