apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: eatcloud
  labels:
    app: order-service
    service: business
spec:
  ports:
  - port: 8086
    targetPort: 8080
    name: http
  selector:
    app: order-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: eatcloud
  labels:
    app: order-service
    service: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        service: business
    spec:
      containers:
      - name: order-service
        image: eatcloud/order-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_PROFILES_ACTIVE
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: ORDER_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: order-db-config
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: REDIS_PORT
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_CLIENT_ENABLED
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_CLIENT_ENABLED
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_KAFKA_BOOTSTRAP_SERVERS
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "750m"
        imagePullPolicy: IfNotPresent
