nameOverride: ""
fullnameOverride: ""

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []  # minikube+ECR면 values에서 override

replicaCount: 1

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: example.local
  path: /
