# deploy/charts/app/values.yaml (또는 각 서비스 values에서 override)
replicaCount: 2

rollout:
  enabled: true              # ← 켜면 Deployment 대신 Rollout 렌더
  steps:
    - setWeight: 10
    - pause: { duration: 60s }
    - setWeight: 50
    - pause: {}              # 수동 승인 지점(무기한)
    - setWeight: 100

image:
  repository: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/eatcloud-auth-service
  tag: "0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-pull

service:
  port: 8080

ingress:
  enabled: true
  className: alb        # ← nginx → alb 로 변경
  host: ""              # 도메인 쓰면 입력, 없으면 빈 값 OK
  path: /
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing   # 내부면 internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health   # 앱 경로에 맞게
