# deploy/charts/app/values.yaml (또는 각 서비스 values에서 override)
replicaCount: 2

rollout:
  enabled: true              # ← 켜면 Deployment 대신 Rollout 렌더
  steps:
    - setWeight: 10
    - pause: { duration: 60s }
    - setWeight: 50
    - pause: {}              # 수동 승인 지점(무기한)
    - setWeight: 100

image:
  repository: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/eatcloud-auth-service
  tag: "0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-pull

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: auth.local
  path: /
