# deploy/charts/app/values.yaml (또는 각 서비스 values에서 override)
replicaCount: 2

rollout:
  enabled: true
  traffic:
    alb:
      enabled: true
      ingress: auth-service-app
      servicePort: 8080
      rootService: auth-service-app
    nginx:
      enabled: true

image:
  repository: <ACCOUNT_ID>.dkr.ecr.ap-northeast-2.amazonaws.com/eatcloud-auth-service
  tag: "0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-pull

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  host: auth.local
  path: /
